config/routes.rb
Rails.application.routes.draw do
  resources :stat_types

  resources :teams do
    member do
      post 'add_player'
      post 'remove_player'
      post 'add_jersey_to_player'
      post 'recover_jersey_from_player'
      post 'increment_player_stat'
      post 'decrement_player_stat'
    end
  end

  resources :players

  root 'welcome#index'

end

app/controllers/stat_types_controller.rb
class StatTypesController < ApplicationController
  before_action :set_stat_type, only: [:show, :edit, :update, :destroy]

  # GET /stat_types
  # GET /stat_types.json
  def index
    @stat_types = StatType.all
  end

  # GET /stat_types/1
  # GET /stat_types/1.json
  def show
  end

  # GET /stat_types/new
  def new
    @stat_type = StatType.new
  end

  # GET /stat_types/1/edit
  def edit
  end

  # POST /stat_types
  # POST /stat_types.json
  def create
    @stat_type = StatType.new(stat_type_params)

    respond_to do |format|
      if @stat_type.save
        format.html { redirect_to @stat_type, notice: 'Stat type was successfully created.' }
        format.json { render :show, status: :created, location: @stat_type }
      else
        format.html { render :new }
        format.json { render json: @stat_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stat_types/1
  # PATCH/PUT /stat_types/1.json
  def update
    respond_to do |format|
      if @stat_type.update(stat_type_params)
        format.html { redirect_to @stat_type, notice: 'Stat type was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat_type }
      else
        format.html { render :edit }
        format.json { render json: @stat_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stat_types/1
  # DELETE /stat_types/1.json
  def destroy
    @stat_type.destroy
    respond_to do |format|
      format.html { redirect_to stat_types_url, notice: 'Stat type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat_type
      @stat_type = StatType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_type_params
      params.require(:stat_type).permit(:name)
    end
end

app/helpers/stat_types_helper.rb
module StatTypesHelper
end

app/views/stat_types/_form.html.erb
<%= form_for(@stat_type) do |f| %>
  <% if @stat_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat_type.errors.count, "error") %> prohibited this stat_type from being saved:</h2>

      <ul>
      <% @stat_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.text_field :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stat_types/edit.html.erb
<h1>Editing stat_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat_type %> |
<%= link_to 'Back', stat_types_path %>

app/views/stat_types/index.html.erb
<h1>Listing stat_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stat_types.each do |stat_type| %>
      <tr>
        <td><%= stat_type.name %></td>
        <td><%= link_to 'Show', stat_type %></td>
        <td><%= link_to 'Edit', edit_stat_type_path(stat_type) %></td>
        <td><%= link_to 'Destroy', stat_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat type', new_stat_type_path %>

app/views/stat_types/new.html.erb
<h1>New stat_type</h1>

<%= render 'form' %>

<%= link_to 'Back', stat_types_path %>

app/views/stat_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stat_type.name %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @stat_type.identifier %>
</p>

<%= link_to 'Edit', edit_stat_type_path(@stat_type) %> |
<%= link_to 'Back', stat_types_path %>