config/routes.rb
Rails.application.routes.draw do
  resources :stat_types

  resources :teams do
    member do
      post 'add_player'
      post 'remove_player'
      post 'add_jersey_to_player'
      post 'recover_jersey_from_player'
      post 'increment_player_stat'
      post 'decrement_player_stat'
    end
  end

  resources :players

  root 'welcome#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :stats, dependent: :destroy
  has_many :teams_players, dependent: :destroy
  has_many :teams, through: :teams_players

  before_validation :build_combined_name

  validates :first_name, :last_name, presence: true
  validates :combined_name, uniqueness: { message: "Another player with a too-similar name already exists" }

  def full_name
    [first_name, last_name].reject(&:empty?).join(" ")
  end

  def player_team(team)
    team.present? ? teams_players.find_by(team_id: team.id) : nil
  end

  def team_jersey(team)
    found_team = player_team(team)
    found_team.present? ? found_team.jersey : ""
  end

  def player_stat(stat_type)
    found_stat = stat_type.present? ? stats.find_by(stat_type_id: stat_type.id, team_id: nil) : nil
    found_stat.nil? ? EmptyStat.new : found_stat
  end

  def team_stat(stat_type, team)
    found_stat = (stat_type.present? && team.present?) ? stats.find_by(stat_type_id: stat_type.id, team_id: team.id) : nil
    found_stat.nil? ? EmptyStat.new : found_stat
  end

  def team_stat_value(stat_type, team)
    team_stat(stat_type, team).value
  end

  def total_stat_value(stat_type)
    found_stats = self.stats.where(stat_type_id: stat_type.id)
    found_stats.to_a.inject(0){ |sum, stat| sum + stat.value }
  end

  private

  def build_combined_name
    self.combined_name = Manipulator.combine(first_name, last_name)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @teams_list = [EmptyTeam.new] + @player.teams.to_a
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    @team = Team.find_by(id: params[:team_id])
    @jersey = params[:jersey]

    respond_to do |format|
      if @player.save
        if @team.present?
          @team.add_player(@player, @jersey)
          format.html { redirect_to @team, notice: 'Player was successfully created and added.' }
          format.json { render :show, status: :created, location: @player }
        else
          format.html { redirect_to @player, notice: 'Player was successfully created.' }
          format.json { render :show, status: :created, location: @player }
        end
      else
        @team_id = params[:team_id]
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <%= hidden_field_tag :team_id, @team_id %>
    <%= hidden_field_tag :jersey, @jersey %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Teams</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td><%= player.teams.count %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>on Teams:</strong>
  <table>
    <thead>
      <tr>
        <th>Team Name</th>
        <th>Jersey</th>
        <% StatType.find_each do |stat_type| %>
          <th><%= stat_type.name %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @teams_list.each do |team| %>
        <tr>
          <td>
            <% if team.empty_team? %>
              <strong><%= team.name %></strong>
            <% else %>
              <%= link_to team.name, team_path(team) %>
            <% end %>
          </td>
          <td class="number"><%= @player.team_jersey(team) %></td>
          <% StatType.find_each do |stat_type| %>
            <td class="centered"><%= display_number(@player.team_stat_value(stat_type, team)) %></td>
          <% end %>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td><strong>Total:</strong></td>
        <% StatType.find_each do |stat_type| %>
          <td class="centered"><strong><%= display_number(@player.total_stat_value(stat_type)) %></strong></td>
        <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>